# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Test with pytest
      #   run: |
      #     if [ -d tests ] || [ -d test ]; then python -m pytest; fi
      - name: Generate Report
        run: |
          coverage run -m pytest
          coverage report  -m --omit="test*"
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
